name: CI
permissions:
  contents: write
  pull-requests: write
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
jobs:
  pr-validation:
    runs-on: ubuntu-latest
    name: PR Conventional Commit Validation
    steps:
      - name: PR Conventional Commit Validation
        uses:  ytanikin/pr-conventional-commits@6ac1cea04190fc076b0e539025501d7e7d241ac1 # 1.4.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
  test:
    runs-on: ubuntu-latest
    name: Update Coverage Badge
    needs: pr-validation # This job may push a commit, which will prevent PR validation check from succeeding.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Run Test
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out
      - name: Go Coverage Badge  # Pass the `coverage.out` output to this action
        uses: tj-actions/coverage-badge-go@84540b9f82b4f569ac9f248cf6f2893ac3cc4791 # v2
        with:
          filename: coverage.out
          link: ${{ github.server_url }}/${{ github.repository }}/actions/workflows/test.yaml
      - name: Verify Changed Files
        uses: tj-actions/verify-changed-files@2acec78834cc690f70b3445712363fc314224127 # v17
        id: verify-changed-files
        with:
          files: README.md
      - name: Commit Changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: Updated coverage badge."
      - name: Push Changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df # v0.8.0
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.head_ref }}
